# Generated by Django 3.0.7 on 2020-12-06 08:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201206_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='profile_pics'),
        ),
    ]
