# Generated by Django 3.0.7 on 2020-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201206_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='raw_file',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics'),
        ),
    ]
