# Generated by Django 3.0.7 on 2020-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link_Image')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
    ]
