# Generated by Django 3.0.7 on 2020-10-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
